import 'package:flutter/material.dart';

class FeaturePage extends StatefulWidget {
  const FeaturePage({Key? key}) : super(key: key);

  @override
  _FeaturePageState createState() => _FeaturePageState();
}

class _FeaturePageState extends State<FeaturePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(backgroundColor: Colors.teal,title: Text('FAQs'),centerTitle: true,),
      body: Container(
        margin: EdgeInsets.symmetric(horizontal: 10,vertical: 15),
        decoration: BoxDecoration(
          border: Border.all(
            color: Colors.grey
          ),
        ),
        padding: EdgeInsets.all(25),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('What features are available in Pocket Password App?',style: TextStyle(fontWeight: FontWeight.w500,fontSize: 14),),
            SizedBox(height: 15,),
            Text('With PPA you can:',style: TextStyle(color: Colors.grey),),
            SizedBox(height: 15,),
            Text('1. All Passwords that save in the app are secure because anyone cannot acesss the app data without login. ',style: TextStyle(color: Colors.grey),),
            SizedBox(height: 10,),
            Text('2. Onlly one account is create in one device. ',style: TextStyle(color: Colors.grey),),
            SizedBox(height: 10,),
            Text('3. You can create simple password,tough password and custom password and save it.',style: TextStyle(color: Colors.grey),),
            SizedBox(height: 10,),
            Text('4. All the passwords are save in locall memory.',style: TextStyle(color: Colors.grey),),
            SizedBox(height: 10,),
            Text('5. In simple password, password are generated by app randomly.',style: TextStyle(color: Colors.grey),),
            SizedBox(height: 10,),
            Text('6. In tough password, password are generated by app randomly based on user input e.g: how many digit, character etc.',style: TextStyle(color: Colors.grey),),
            SizedBox(height: 10,),
            Text('7. In Custom password, password are create by user.',style: TextStyle(color: Colors.grey),),
            SizedBox(height: 10,),
            Text('8. App provide facility to update and delete any password.',style: TextStyle(color: Colors.grey),),
            SizedBox(height: 10,),
            Text('9. App provide facility to copy and share the password',style: TextStyle(color: Colors.grey),),
            SizedBox(height: 10,),
            Text('10. App provide facility to convert all password in PDF form and you can download the PDF or upload to Gooogle Drive.',style: TextStyle(color: Colors.grey),),

          ],
        ),
      ),
    );
  }
}
